# Start from a Java SE 21 base image
FROM openjdk:21-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the pom.xml and source code into the image
COPY . .

# Install dependencies and compile the project
RUN mvn package

# The application's jar file will be output to the /target directory
# Change 'app.jar' to your built jar file name
CMD ["java", "-jar", "/app/target/app.jar"]
