FROM node:20.9.0-alpine

RUN apk add --no-cache bash curl

SHELL ["/bin/bash", "-c"]

RUN npm i befunge93 \
    && curl -L https://gist.githubusercontent.com/Octopus773/af90e3164cbb5a2cfeb786f0590a89a6/raw/e0ae92fd1ea8fa8e5030605f3797f43837c3430f/befunge93-cli.js\
    > /opt/befunge93-cli.js

ONBUILD COPY . /app

ONBUILD WORKDIR /app

ONBUILD CMD node /opt/befunge93-cli.js -f app/main.bf